# Generated by Django 5.2.7 on 2025-10-10 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_categorias', models.JSONField(blank=True, default=dict, help_text="Ordem de prioridade das categorias em formato JSON, ex: {'categoria_id': ordem}")),
                ('categorias', models.ManyToManyField(blank=True, related_name='preferencias_usuarios', to='noticias.categoria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_feed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Feed',
                'verbose_name_plural': 'Preferências de Feed',
            },
        ),
    ]
