# Generated by Django 5.2.6 on 2025-10-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_preferenciasfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='noticias.categoria'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
