# Generated by Django 5.2.6 on 2025-10-19 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_categoria_slug_noticia_categoria_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_escritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
