# Generated by Django 5.2.6 on 2025-11-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_alter_comentario_options_remove_comentario_autor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreferenciasFeed',
        ),
    ]
