# Generated by Django 5.2.6 on 2025-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_delete_preferenciasfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagens/', verbose_name='Imagem de Destaque'),
        ),
    ]
