# Generated by Django 5.2.6 on 2025-11-08 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_noticia_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_curtida', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='noticias.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['noticia'], name='noticias_cu_noticia_94df56_idx'), models.Index(fields=['usuario'], name='noticias_cu_usuario_7cb127_idx')],
                'unique_together': {('usuario', 'noticia')},
            },
        ),
    ]
