# Generated by Django 5.2.6 on 2025-11-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_curtida'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.TextField(blank=True, null=True, verbose_name='Sub-título'),
        ),
    ]
