# Generated by Django 5.2.6 on 2025-11-13 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_noticia_subtitulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.IntegerField(default=99, help_text='Defina a ordem de prioridade (0, 1, 2...). Categorias com números menores aparecem primeiro.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='viu_personalizacao',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PreferenciasFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias_ordenadas', models.JSONField(blank=True, default=list, help_text='Lista de slugs de categoria na ordem de preferência do usuário.')),
                ('personalizacao_ativa', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_feed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Feed',
                'verbose_name_plural': 'Preferências de Feed',
            },
        ),
    ]
