# Generated by Django 5.2.6 on 2025-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_alter_categoria_options_categoria_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem_credito',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Crédito da Imagem'),
        ),
    ]
