# Generated by Django 5.2.6 on 2025-11-21 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0012_noticia_imagem_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('content_preview', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_emails', models.BooleanField(default=True, verbose_name='Quero receber notícias por e-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(blank=True, to='noticias.categoria', verbose_name='Categorias de interesse')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
